=== citosid/raml-akamai/schemas/getRTMPStreamDTO.json
{
  "$schema": "http://json-schema.org/draft-04-schema#",
  "id": "resource:/descriptors/config-media-live/v1/schemas/getRTMPStreamDTO.json#",
  "type": "object",
  "description": "Creates a new RTMP stream.",
  "properties": {
    "id": {
      "type": "integer",
      "readOnly": true,
      "description": "A unique ID for your stream."
    },
    "isSecure": {
      "type": "boolean",
      "description": "Specify whether secure profiles are enabled on the stream."
    },
    "createdDate": {
      "type": "string",
      "readOnly": true,
      "format": "date-time",
      "description": "The date and time when your stream is created. It's an ISO 8601 timestamp."
    },
    "primaryEntrypoint": {
      "type": "string",
      "description": "Specifies the URL of the primary entry point that obtain the stream in Media Services Live."
    },
    "backupEntrypoint": {
      "type": "string",
      "description": "Specifies the RTMP URL of the backup entry point that obtain the stream in Media Services Live. You can use the backup entry point when the primary entry point fails."
    },
    "playbackSettings": {
      "$ref": "resource:/descriptors/config-media-live/v1/schemas/PlaybackSetting.json"
    },
    "status": {
      "type": "string",
      "description": "The status of the stream: Provisioned or Not Yet Provisioned."
    },
    "email": {
      "type": "string",
      "description": "The email address to notify that the stream is successfully provisioned."
    },
    "blocked": {
      "type": "boolean",
      "description": "Specify whether the stream is blocked or unblocked. Enable blocked to prevent end users from accessing the stream."
    },
    "cpcode": {
      "type": "integer",
      "description": "The Content Provider code that you assign to the stream."
    },
    "name": {
      "type": "string",
      "description": "The name of your stream. The stream name can be up to 100 characters long and can only include alphanumeric and underscore characters."
    },
    "dynamic": {
      "type": "boolean",
      "description": "Specifies if the stream can publish multiple bitrate streams."
    },
    "encoder": {
      "$ref": "resource:/descriptors/config-media-live/v1/schemas/Encoder.json"
    },
    "streamEndDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time at which you expect your streaming event to end. It's an ISO 8601 timestamp."
    },
    "contactDetails": {
      "$ref": "resource:/descriptors/config-media-live/v1/schemas/ContactDetails.json#"
    },
    "authProfiles": {
      "$ref": "resource:/descriptors/config-media-live/v1/schemas/RTMPAuthInfo.json#"
    }
  },
  "required": [
    "authProfiles",
    "contactDetails",
    "cpcode",
    "dynamic",
    "email",
    "encoder",
    "name",
    "streamEndDate"
  ]
}

=== citosid/raml-akamai/examples/RTMP-Stream-details.json
{
  "isSecure": true,
  "createdDate": "2018-10-15T10:18:23.000Z",
  "primaryEntrypoint": "rtmp://p.ep123456.i.exampleentrypoint.net/EntryPoint",
  "backupEntrypoint": "rtmp://b.ep123456.i.exampleentrypoint.net/EntryPoint",
  "playbackSettings": [
    {
      "connectionUrl": "rtmp://exampleConnectionUrl.net/live/",
      "playbackUrl": "StreamTemp123@s123456"
    }
  ],
  "status": "Not Yet Provisioned",
  "email": "user@example.com",
  "blocked": false,
  "id": 123456,
  "cpcode": 65432,
  "name": "StreamTemp123",
  "dynamic": true,
  "encoder": {
    "primaryEncoderIP": "1.1.1.1",
    "backupEncoderIP": "198.199.26.36",
    "password": "abc123"
  },
  "streamEndDate": "2019-03-30T18:30:00.000Z",
  "contactDetails": {
    "primary": "Jack King",
    "secondary": "Aditya Sharma"
  },
  "authProfiles": [
    {
      "name": "abctemp",
      "password": "abc123",
      "eTokenType": "NO_CHANGE",
      "requireIP": true,
      "requirePath": true,
      "requirePayload": true,
      "cidr": "1.2.3.4/12"
    }
  ]
}

=== citosid/raml-akamai/examples/RTMP-Stream-edit.json
{
  "cpcode": 123456,
  "name": "TempStream",
  "dynamic": true,
  "email": "abc@example.com",
  "streamEndDate": "2019-03-30T18:30:00.000Z",
  "encoder": {
    "password": "abc123",
    "primaryEncoderIP": "1.1.1.1",
    "backupEncoderIP": "1.1.1.1"
  },
  "contactDetails": {
    "primary": "user test",
    "secondary": "user test"
  },
  "authProfiles": [
    {
      "name": "abctemp",
      "password": "abc123",
      "eTokenType": "NO_CHANGE",
      "requireIP": true,
      "requirePath": true,
      "requirePayload": true,
      "cidr": "1.2.3.4/12"
    }
  ]
}

=== citosid/raml-akamai/examples/RTMP-Stream-create.json
{
  "cpcode": 12345,
  "name": "testStream",
  "dynamic": true,
  "encoder": {
    "primaryEncoderIP": "1.1.1.1",
    "backupEncoderIP": "1.1.1.1",
    "password": "test123"
  },
  "contactDetails": {
    "primary": "User test",
    "secondary": "User test"
  },
  "email": "abc@example.com",
  "isSecure": true,
  "streamEndDate": "2019-02-27T18:30:00.000Z",
  "authProfiles": [
    {
      "eTokenType": "NEW",
      "requireIP": true,
      "requirePath": true,
      "requirePayload": true,
      "name": "temp",
      "password": "abc123",
      "cidr": "1.2.3.4-1.2.3.4"
    }
  ]
}
