=== citosid/raml-akamai/schemas/getRTMPConfigurationDTO.json
{
  "$schema": "http://json-schema.org/draft-04-schema#",
  "id": "resource:/descriptors/config-media-live/v1/schemas/getRTMPConfigurationDTO.json#",
  "type": "object",
  "properties": {
    "swfLocation": {
      "type": "string",
      "description": "NetStorage location of the validated player used for player verification."
    },
    "isSecure": {
      "type": "boolean",
      "description": "Specify whether to enable the security profiles for your stream."
    },
    "createdDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when the RTMP configuration was created."
    },
    "isHDConfig": {
      "type": "boolean",
      "description": "Specify whether your configuration is associated with the stream packaging type."
    },
    "name": {
      "type": "string",
      "description": "The unique name that you give to your configuration."
    },
    "cpcode": {
      "type": "integer",
      "description": "The Content Provider code name associated with your RTMP configuration."
    },
    "usePreSpreadSerial": {
      "type": "boolean",
      "description": "Specify whether to use the standard protocol port for streaming."
    },
    "hostAliases": {
      "type": "array",
      "description": "Alias provided to the default hostname. To stream content on these hostnames, you must create them on your DNS server as CNAME records pointing to the default hostname.",
      "items": {
        "type": "string"
      }
    },
    "authProfiles": {
      "$ref": "resource:/descriptors/config-media-live/v1/schemas/RTMPAuthInfo.json#"
    },
    "swfPath": {
      "type": "string",
      "description": "Netstorage path of the validated player used for player verification."
    },
    "isRtmpe": {
      "type": "boolean",
      "description": "Specify whether to enable use of RTMPE/RTMPTE protocols. This denies all other protocols (RTMP/RTMPT)."
    },
    "isMbr": {
      "type": "boolean",
      "description": "Specify whether to enable Dynamic/MBR (multiple bitrate) feature for your stream."
    }
  }
}

=== citosid/raml-akamai/examples/RTMP-Flash-config-create.json
{
  "name": "testConfig123",
  "cpcode": 12345,
  "usePreSpreadSerial": true,
  "hostAliases": [
    "testHost1",
    "testHost2",
    "testHost3"
  ],
  "isRtmpe": false,
  "isMbr": false,
  "isSecure": true,
  "swfPath": "temp",
  "swfLocation": "123456.download.example.com/123456/",
  "authProfiles": [
    {
      "eTokenType": "NEW",
      "requireIP": true,
      "requirePath": true,
      "requirePayload": true,
      "name": "temp",
      "password": "abc123",
      "cidr": "1.2.3.4/32"
    }
  ]
}

=== citosid/raml-akamai/examples/RTMP-Flash-config-details.json
{
  "name": "samplename",
  "cpcode": 12345,
  "isSecure": true,
  "authProfiles": [
    {
      "name": "temp",
      "password": "abc123",
      "eTokenType": "NO_CHANGE",
      "requireIP": true,
      "requirePath": false,
      "requirePayload": true,
      "cidr": "1.2.3.4-4.5.6.7"
    }
  ],
  "usePreSpreadSerial": true,
  "hostAliases": [
    "default.hostname.net (default)",
    "testHost1.com",
    "testHost2.com"
  ], 
  "swfPath": "check123",
  "swfLocation": "654321.download.example.com/654321/",
  "isRtmpe": true,
  "isMbr": true
}

=== citosid/raml-akamai/examples/RTMP-Flash-confg-edit.json
{
  "name": "sampleConfig",
  "cpcode": 1234,
  "usePreSpreadSerial": true,
  "isRtmpe": true,
  "isMbr": true,
  "isSecure": true,
  "hostAliases": [
    "testHost1",
    "testHost2"
  ],
  "swfPath": "check123",
  "swfLocation": "654321.download.example.com/654321/",
  "authProfiles": [
    {
      "name": "tempAuthProf",
      "password": "abc123",
      "eTokenType": "NO_CHANGE",
      "requireIP": true,
      "requirePath": true,
      "requirePayload": true,
      "cidr": "1.2.3.4-1.2.3.4"
    }
  ]
}
